import 'package:dotto/domain/floor.dart';
import 'package:dotto/domain/map_tile_props.dart';

abstract class FUNMapGrid {
  static final List<MapTileProps> mapTileProps = [
    AtriumMapTileProps(
      floor: Floor.first,
      width: 48,
      height: 18,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AtriumMapTileProps(
      floor: Floor.first,
      width: 40,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 8,
      height: 7,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 40,
      height: 1,
      top: 1,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 3,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 4,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '155',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '154',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '153',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '152',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '151',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
  ];
}
