import 'package:dotto/domain/floor.dart';
import 'package:dotto/domain/map_stair_type.dart';
import 'package:dotto/domain/map_tile_props.dart';
import 'package:dotto/domain/restroom_type.dart';
import 'package:dotto/domain/room_equipment.dart';
import 'package:flutter/material.dart';

abstract class FUNMapGrid {
  static final List<MapTileProps> mapTileProps = [
    /// 1F
    AtriumMapTileProps(
      floor: Floor.first,
      width: 48,
      height: 18,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AtriumMapTileProps(
      floor: Floor.first,
      width: 40,
      height: 7,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 8,
      height: 7,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 40,
      height: 1,
      top: 1,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 3,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 4,
      top: 0,
      right: 1,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '155',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '154',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '153',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '152',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '151',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    // アトリエ側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 3,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.women, RestroomType.kitchenette],
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '150',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '149',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '148',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '147',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '146',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '145',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '144',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '143',
    ),
    // 食堂側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.women],
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    // 食堂側トイレ
    RestroomMapTileProps(
      floor: Floor.first,
      width: 3,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      types: [RestroomType.men, RestroomType.multipurpose],
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '135',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '134',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '133',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '132',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '131',
    ),
    StairMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '130',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '129',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '128',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '127',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '126',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '125',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '124',
    ),
    FacultyRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '123',
    ),
    SubRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '122',
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 1,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    SubRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      id: '121',
    ),
    StairMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 4,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
      type: const MapStairType(Axis.vertical, up: true, down: false),
    ),
    SubRoomMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 16,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      id: '',
      label: '食堂',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 42,
      height: 1,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 12,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 10,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 18,
      height: 3,
      top: 0,
      right: 1,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 1,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    ElevatorMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 1,
      right: 1,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 18,
      height: 3,
      top: 0,
      right: 1,
      bottom: 0,
      left: 1,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 1,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 1,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 1,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 6,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    // アトリエ
    ClassroomMapTileProps(
      floor: Floor.first,
      width: 12,
      height: 6,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      id: 'アトリエ',
      equipment: RoomEquipmentStatus(
        outlet: RoomEquipmentOutlet(quality: RoomEquipmentQuality.available),
        food: RoomEquipmentFood(quality: RoomEquipmentQuality.unavailable),
        drink: RoomEquipmentDrink(quality: RoomEquipmentQuality.available),
      ),
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 18,
      height: 1,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 1,
      label: 'プレゼンテーションベイB',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
      label: 'プレゼンテーションベイG',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 6,
      height: 5,
      top: 0,
      right: 1,
      bottom: 1,
      left: 0,
      label: 'プレゼンテーションベイR',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
    ),
    OtherRoomMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      label: '出入口',
    ),
    AisleMapTileProps(
      floor: Floor.first,
      width: 2,
      height: 2,
      top: 0,
      right: 0,
      bottom: 1,
      left: 0,
    ),

    /// 2F
  ];
}
