import 'package:dotto/domain/map_stair_type.dart';
import 'package:dotto/feature/map/domain/map_tile_type.dart';
import 'package:dotto/feature/map/widget/consumer_map_tile.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

abstract final class FunGridMaps {
  static final Map<String, List<ConsumerMapTile>> mapTileListMap = {
    '1': [
      ConsumerMapTile(48, 18, MapTileType.empty),
      ConsumerMapTile(40, 7, MapTileType.empty),
      ConsumerMapTile(8, 7, MapTileType.otherroom, left: 1, top: 1, right: 1),
      ConsumerMapTile(40, 1, MapTileType.road, left: 1, top: 1),
      ConsumerMapTile(2, 3, MapTileType.otherroom),
      ConsumerMapTile(6, 4, MapTileType.otherroom, right: 1),
      ConsumerMapTile(1, 6, MapTileType.road, left: 1),
      ConsumerMapTile(1, 6, MapTileType.otherroom),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '155'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '154'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '153'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '152'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '151'),
      ConsumerMapTile(1, 6, MapTileType.road),
      ConsumerMapTile(3, 6, MapTileType.wc, wc: 0x1101), // アトリエ側トイレ
      ConsumerMapTile(2, 2, MapTileType.otherroom),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '150'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '149'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '148'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '147'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '146'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '145'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '144'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '143'),
      ConsumerMapTile(2, 2, MapTileType.wc, wc: 0x0100), // 食堂側トイレ
      ConsumerMapTile(1, 6, MapTileType.road),
      ConsumerMapTile(3, 2, MapTileType.wc, wc: 0x1010), // 食堂側トイレ
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '135'), //135
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '134'), //134
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '133'), //133
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '132'), //132
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '131'), //131
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        top: 1,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '130'), //130
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '129'), //129
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '128'), //128
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '127'), //127
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '126'), //126
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '125'), //125
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '124'), //124
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '123'), //123
      ConsumerMapTile(2, 4, MapTileType.subroom, txt: '122'), //122
      ConsumerMapTile(1, 4, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.subroom, txt: '121'), //121
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        top: 1,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ),
      ConsumerMapTile(
        6,
        16,
        MapTileType.subroom,
        right: 1,
        bottom: 1,
        txt: '食堂',
      ), //食堂
      ConsumerMapTile(42, 1, MapTileType.road, left: 1),
      ConsumerMapTile(12, 6, MapTileType.otherroom, left: 1),
      ConsumerMapTile(6, 10, MapTileType.road),
      ConsumerMapTile(18, 3, MapTileType.otherroom, right: 1, left: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.ev, left: 1, top: 1, right: 1), //ev
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(18, 3, MapTileType.road, right: 1, left: 1),
      ConsumerMapTile(2, 1, MapTileType.road),
      ConsumerMapTile(2, 1, MapTileType.road, bottom: 1),
      ConsumerMapTile(2, 1, MapTileType.road),
      ConsumerMapTile(6, 6, MapTileType.road),
      ConsumerMapTile(
        12,
        6,
        MapTileType.classroom,
        classroomNo: '50',
        txt: 'アトリエ',
        left: 1,
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ), //アトリエ
      ConsumerMapTile(18, 1, MapTileType.road),
      ConsumerMapTile(
        6,
        5,
        MapTileType.road,
        left: 1,
        bottom: 1,
        txt: 'プレゼンテーションベイB',
      ),
      ConsumerMapTile(6, 5, MapTileType.road, bottom: 1, txt: 'プレゼンテーションベイG'),
      ConsumerMapTile(
        6,
        5,
        MapTileType.road,
        right: 1,
        bottom: 1,
        txt: 'プレゼンテーションベイR',
      ),
      ConsumerMapTile(2, 2, MapTileType.road, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.road, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.road, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.otherroom, txt: '出入口'),
      ConsumerMapTile(2, 2, MapTileType.road, bottom: 1),
    ],
    '2': [
      ConsumerMapTile(48, 18, MapTileType.empty),
      ConsumerMapTile(40, 1, MapTileType.road, left: 1, top: 1),
      ConsumerMapTile(2, 3, MapTileType.otherroom, top: 1),
      ConsumerMapTile(6, 7, MapTileType.otherroom, top: 1, right: 1),
      ConsumerMapTile(1, 6, MapTileType.road, left: 1),
      ConsumerMapTile(3, 2, MapTileType.teacherroom, txt: '255'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '254'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '253'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '252'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '251'),
      ConsumerMapTile(1, 6, MapTileType.road),
      ConsumerMapTile(3, 6, MapTileType.wc, wc: 0x1101), // アトリエ側トイレ
      ConsumerMapTile(2, 2, MapTileType.otherroom),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '250'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '249'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '248'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '247'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '246'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '245'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '244'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '243'),
      ConsumerMapTile(2, 2, MapTileType.wc, wc: 0x0100), // 購買側トイレ
      ConsumerMapTile(1, 6, MapTileType.road),
      ConsumerMapTile(3, 2, MapTileType.wc, wc: 0x1010), // 購買側トイレ
      ConsumerMapTile(1, 4, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '235'), //235
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '234'), //234
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '233'), //233
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '232'), //232
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '231'), //231
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        top: 1,
        right: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ), // アトリエ側階段
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '230'), //230
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '229'), //229
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '228'), //228
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '227'), //227
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '226'), //226
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '225'), //225
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '224'), //224
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '223'), //223
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '222'), //222
      ConsumerMapTile(1, 4, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.subroom, txt: '221'), //221
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        top: 1,
        right: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ), // 購買側階段
      ConsumerMapTile(42, 1, MapTileType.road, left: 1),
      ConsumerMapTile(
        6,
        6,
        MapTileType.subroom,
        txt: '購買',
        right: 1,
        bottom: 1,
      ), //売店
      ConsumerMapTile(12, 5, MapTileType.otherroom, left: 1, bottom: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(17, 2, MapTileType.otherroom),
      ConsumerMapTile(1, 2, MapTileType.road, right: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(4, 4, MapTileType.road, bottom: 1),
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        right: 1,
        bottom: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ),
      ConsumerMapTile(4, 4, MapTileType.road),
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        right: 1,
        bottom: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ),
      ConsumerMapTile(18, 3, MapTileType.road, bottom: 1),
      ConsumerMapTile(36, 6, MapTileType.empty), //empty
      ConsumerMapTile(2, 6, MapTileType.road, left: 1, bottom: 1),
      ConsumerMapTile(10, 2, MapTileType.empty, top: 1, left: 1),
      ConsumerMapTile(2, 2, MapTileType.ev, top: 1, right: 1, left: 1), //ev
      ConsumerMapTile(8, 2, MapTileType.empty), //empty
      ConsumerMapTile(2, 1, MapTileType.road, right: 1, bottom: 1),
      ConsumerMapTile(8, 1, MapTileType.empty), //empty
      ConsumerMapTile(10, 1, MapTileType.empty, left: 1), //empty
    ],
    '3': [
      ConsumerMapTile(
        12,
        18,
        MapTileType.classroom,
        txt: '体育館',
        top: 1,
        left: 1,
        classroomNo: '51',
        food: false,
        drink: true,
      ),
      ConsumerMapTile(
        6,
        6,
        MapTileType.subroom,
        top: 1,
        txt: 'トレーニングルーム',
        food: false,
        drink: true,
      ),
      ConsumerMapTile(30, 6, MapTileType.empty, left: 1),
      ConsumerMapTile(4, 4, MapTileType.wc, wc: 0x1110), // 体育館トイレ
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(
        6,
        12,
        MapTileType.classroom,
        txt: '工房',
        top: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        12,
        MapTileType.classroom,
        txt: 'エレクトロニクス工房',
        top: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(6, 2, MapTileType.subroom, txt: '医務室', top: 1),
      ConsumerMapTile(2, 2, MapTileType.road, txt: '休日夜間入口'),
      ConsumerMapTile(6, 2, MapTileType.otherroom, top: 1),
      ConsumerMapTile(4, 3, MapTileType.otherroom, top: 1, right: 1),
      ConsumerMapTile(
        6,
        4,
        MapTileType.subroom,
        txt: '映像音響スタジオ',
        food: false,
        drink: false,
      ),
      ConsumerMapTile(2, 10, MapTileType.road),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(4, 3, MapTileType.otherroom),
      ConsumerMapTile(6, 2, MapTileType.otherroom, right: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom),
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ), // 体育館側階段
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        6,
        7,
        MapTileType.subroom,
        txt: 'ミュージアム',
        right: 1,
        food: false,
        drink: true,
      ),
      ConsumerMapTile(6, 2, MapTileType.road),
      ConsumerMapTile(6, 6, MapTileType.subroom, txt: '社会連携センター'),
      ConsumerMapTile(2, 6, MapTileType.wc, wc: 0x1100), // 駐車場側トイレ
      ConsumerMapTile(
        2,
        5,
        MapTileType.stair,
        top: 1,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ), // 事務局行き階段
      ConsumerMapTile(4, 4, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(2, 1, MapTileType.road),
      ConsumerMapTile(48, 2, MapTileType.road, left: 1, right: 1), // モール
      ConsumerMapTile(2, 2, MapTileType.otherroom, txt: '研究棟入口'),
      ConsumerMapTile(12, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ), // モール体育館側階段
      ConsumerMapTile(18, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.ev,
        top: 1,
        left: 1,
        bottom: 1,
      ), // モールエレベーター
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ), // モール入口側階段
      ConsumerMapTile(6, 2, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.otherroom, txt: '正面\n入口'),
      ConsumerMapTile(48, 2, MapTileType.road, left: 1, right: 1), // モール
      ConsumerMapTile(
        12,
        7,
        MapTileType.classroom,
        txt: '大講義室',
        left: 1,
        classroomNo: '2',
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(1, 7, MapTileType.otherroom),
      ConsumerMapTile(
        3,
        5,
        MapTileType.subroom,
        txt: '心理学実験室',
        food: false,
        drink: false,
      ),
      ConsumerMapTile(2, 7, MapTileType.road),
      ConsumerMapTile(
        6,
        7,
        MapTileType.classroom,
        txt: '365',
        classroomNo: '18',
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        7,
        MapTileType.classroom,
        txt: '364',
        classroomNo: '17',
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        7,
        MapTileType.classroom,
        txt: '363',
        classroomNo: '16',
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(4, 2, MapTileType.otherroom),
      ConsumerMapTile(2, 7, MapTileType.road),
      ConsumerMapTile(
        6,
        37,
        MapTileType.subroom,
        txt: 'ライブラリ',
        right: 1,
        bottom: 1,
        left: 1,
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(2, 5, MapTileType.wc, wc: 0x1000), // 入口側トイレ男
      ConsumerMapTile(2, 5, MapTileType.otherroom),
      ConsumerMapTile(3, 2, MapTileType.otherroom),
      ConsumerMapTile(42, 1, MapTileType.road, left: 1),
      ConsumerMapTile(1, 6, MapTileType.road, left: 1),
      ConsumerMapTile(3, 2, MapTileType.teacherroom, txt: '355'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '354'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '353'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '352'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '351'),
      ConsumerMapTile(4, 4, MapTileType.wc, wc: 0x1101), // 331側トイレ
      ConsumerMapTile(2, 6, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '350'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '349'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '348'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '347'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '346'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '345'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '344'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '343'),
      ConsumerMapTile(2, 2, MapTileType.teacherroom, txt: '342'),
      ConsumerMapTile(4, 2, MapTileType.wc, wc: 0x0110), // 入口側トイレ女
      ConsumerMapTile(2, 6, MapTileType.road),
      ConsumerMapTile(1, 4, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '335'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '334'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '333'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '332'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '331'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '330'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '329'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '328'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '327'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '326'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '325'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '324'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '323'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '322'),
      ConsumerMapTile(2, 4, MapTileType.subroom, txt: '321'),
      ConsumerMapTile(4, 2, MapTileType.otherroom),
      ConsumerMapTile(2, 4, MapTileType.otherroom),
      ConsumerMapTile(42, 1, MapTileType.road, left: 1),
      ConsumerMapTile(12, 5, MapTileType.otherroom, left: 1, bottom: 1),
      ConsumerMapTile(4, 3, MapTileType.road),
      ConsumerMapTile(2, 1, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.otherroom),
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(14, 2, MapTileType.otherroom),
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(4, 3, MapTileType.road),
      ConsumerMapTile(2, 1, MapTileType.road),
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        bottom: 1,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ), // 階段331側下り
      ConsumerMapTile(
        2,
        4,
        MapTileType.stair,
        bottom: 1,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ), // 階段321側下り
      ConsumerMapTile(18, 3, MapTileType.road, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.road, bottom: 1),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ), // 階段331側上り
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ), // 階段321側上り
      ConsumerMapTile(36, 12, MapTileType.empty, right: 1),
      ConsumerMapTile(2, 12, MapTileType.road, bottom: 1),
      ConsumerMapTile(4, 8, MapTileType.empty, left: 1),
      ConsumerMapTile(
        2,
        2,
        MapTileType.ev,
        left: 1,
        top: 1,
        right: 1,
      ), // エレベーター
      ConsumerMapTile(2, 2, MapTileType.empty),
      ConsumerMapTile(2, 1, MapTileType.road, right: 1, bottom: 1),
      ConsumerMapTile(2, 1, MapTileType.empty),
      ConsumerMapTile(4, 1, MapTileType.empty, left: 1),
    ],
    '4': [
      ConsumerMapTile(
        12,
        18,
        MapTileType.otherroom,
        txt: '体育館',
        top: 1,
        left: 1,
        bottom: 1,
        right: 1,
        food: false,
        drink: true,
      ),
      //Tile(6, 6, TileType.empty, left: 1.5),  一応吹き抜けでトレーニングルーム見える
      ConsumerMapTile(36, 6, MapTileType.empty),
      ConsumerMapTile(2, 6, MapTileType.road, top: 1),
      ConsumerMapTile(
        2,
        4,
        MapTileType.wc,
        top: 1,
        right: 1,
        wc: 0x1110,
      ), // 体育館側トイレ
      ConsumerMapTile(2, 6, MapTileType.empty, bottom: 1),
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '495C&D',
        classroomNo: '9',
        top: 1,
        left: 1,
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '494C&D',
        classroomNo: '8',
        top: 1,
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '493',
        classroomNo: '3',
        top: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(2, 6, MapTileType.road, top: 1),
      ConsumerMapTile(2, 6, MapTileType.road, top: 1, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, top: 1, txt: '証明書発行機'),
      ConsumerMapTile(6, 10, MapTileType.subroom, txt: '事務局', top: 1, right: 1),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
      ), // 体育館側階段
      ConsumerMapTile(30, 1, MapTileType.road),
      ConsumerMapTile(2, 13, MapTileType.road),
      ConsumerMapTile(
        2,
        5,
        MapTileType.otherroom,
        txt: '406',
        right: 1,
        bottom: 1,
      ),
      ConsumerMapTile(2, 5, MapTileType.empty, top: 1),
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '485',
        left: 1,
        bottom: 1,
        food: false,
        drink: true,
      ),
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '484',
        classroomNo: '10',
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '483',
        classroomNo: '19',
        bottom: 1,
        food: false,
        drink: false,
        outlet: 2,
      ),
      ConsumerMapTile(2, 13, MapTileType.road),
      ConsumerMapTile(2, 5, MapTileType.wc, bottom: 1, wc: 0x1110), // 事務側トイレ
      ConsumerMapTile(
        2,
        5,
        MapTileType.stair,
        right: 1,
        bottom: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ),
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(
        5,
        2,
        MapTileType.subroom,
        txt: '局長室',
        right: 1,
        bottom: 1,
      ),
      ConsumerMapTile(12, 6, MapTileType.empty, right: 1),
      ConsumerMapTile(22, 2, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(4, 2, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(1, 8, MapTileType.road),
      ConsumerMapTile(5, 6, MapTileType.empty, left: 1),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
      ), // モール体育館側
      ConsumerMapTile(18, 2, MapTileType.empty),
      ConsumerMapTile(
        2,
        2,
        MapTileType.ev,
        txt: 'ev',
        top: 1,
        bottom: 1,
        left: 1,
      ),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
      ), // モール正面玄関側
      ConsumerMapTile(2, 2, MapTileType.empty, right: 1),
      ConsumerMapTile(22, 2, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(4, 2, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(
        2,
        2,
        MapTileType.subroom,
        txt: 'S-15',
        top: 1,
        left: 1,
      ), //文字はみ出してる
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-14', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-13', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-12', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-11', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-10', top: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, top: 1),
      ConsumerMapTile(1, 2, MapTileType.wc, wc: 0x0001, top: 1, right: 1),
      ConsumerMapTile(2, 2, MapTileType.empty, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-9', top: 1, left: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-8', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-7', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-6', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-5', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-4', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-3', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-2', top: 1),
      ConsumerMapTile(2, 2, MapTileType.subroom, txt: 'S-1', top: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, top: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, txt: '倉庫', top: 1, right: 1),
      ConsumerMapTile(2, 2, MapTileType.empty, bottom: 1, right: 1),
      ConsumerMapTile(2, 2, MapTileType.otherroom, top: 1),
      ConsumerMapTile(3, 3, MapTileType.subroom, txt: '理事室', top: 1, right: 1),
      ConsumerMapTile(43, 1, MapTileType.road, left: 1),
      ConsumerMapTile(2, 5, MapTileType.subroom, txt: '秘書室'),
      ConsumerMapTile(1, 4, MapTileType.road, left: 1),
      ConsumerMapTile(1, 4, MapTileType.otherroom, txt: '倉庫'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '435'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '434'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '433'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '432'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '431'),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(2, 3, MapTileType.wc, wc: 0x1100, right: 1),
      ConsumerMapTile(2, 10, MapTileType.empty, top: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, txt: '印刷', left: 1),
      ConsumerMapTile(1, 4, MapTileType.road),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '429'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '428'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '427'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '426'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '425'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '424'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '423'),
      ConsumerMapTile(2, 4, MapTileType.subroom, txt: '422'),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(2, 3, MapTileType.wc, wc: 0x1100, right: 1),
      ConsumerMapTile(2, 10, MapTileType.empty, top: 1, right: 1),
      ConsumerMapTile(1, 9, MapTileType.road),
      ConsumerMapTile(3, 4, MapTileType.subroom, txt: '学長室', right: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, txt: '倉庫', left: 1),
      ConsumerMapTile(2, 1, MapTileType.otherroom, right: 1),
      ConsumerMapTile(2, 1, MapTileType.otherroom, right: 1),
      ConsumerMapTile(14, 1, MapTileType.road, left: 1),
      ConsumerMapTile(2, 3, MapTileType.subroom, txt: 'M402', right: 1),
      ConsumerMapTile(22, 1, MapTileType.road, right: 1, left: 1),
      ConsumerMapTile(5, 4, MapTileType.subroom, txt: '特別応接室', right: 1),
      ConsumerMapTile(12, 5, MapTileType.otherroom, left: 1, bottom: 1),
      ConsumerMapTile(2, 5, MapTileType.road),
      ConsumerMapTile(18, 3, MapTileType.otherroom, left: 1),
      ConsumerMapTile(2, 5, MapTileType.road),
      ConsumerMapTile(2, 5, MapTileType.road, txt: 'ラウンジ', right: 1, bottom: 1),
      ConsumerMapTile(
        2,
        3,
        MapTileType.subroom,
        txt: 'M401',
        bottom: 1,
        right: 1,
      ),
      ConsumerMapTile(6, 2, MapTileType.otherroom, bottom: 1, left: 1),
      ConsumerMapTile(6, 2, MapTileType.classroom, txt: 'メタ学習ラボ', bottom: 1),
      ConsumerMapTile(6, 2, MapTileType.otherroom, bottom: 1),
      ConsumerMapTile(4, 1, MapTileType.otherroom),
      ConsumerMapTile(1, 1, MapTileType.road, right: 1),
      ConsumerMapTile(6, 1, MapTileType.road, right: 1),
      ConsumerMapTile(12, 19, MapTileType.empty, right: 1),
      ConsumerMapTile(2, 7, MapTileType.road),
      ConsumerMapTile(22, 5, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(2, 7, MapTileType.road),
      ConsumerMapTile(4, 5, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(1, 7, MapTileType.road),
      ConsumerMapTile(3, 3, MapTileType.subroom, txt: 'サーバーコンピュータ事務室'),
      ConsumerMapTile(
        2,
        3,
        MapTileType.wc,
        wc: 0x1101,
        right: 1,
      ), // サーバーコンピュータ室側トイレ
      ConsumerMapTile(5, 4, MapTileType.subroom, txt: 'サーバーコンピュータ室', right: 1),
      ConsumerMapTile(2, 2, MapTileType.stair, top: 1, right: 1, bottom: 1),
      ConsumerMapTile(20, 2, MapTileType.empty, bottom: 1, right: 1),
      ConsumerMapTile(2, 2, MapTileType.stair, top: 1, right: 1, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.empty, right: 1),
      ConsumerMapTile(26, 1, MapTileType.road),
      ConsumerMapTile(4, 8, MapTileType.empty, left: 1, right: 1),
      ConsumerMapTile(
        6,
        12,
        MapTileType.classroom,
        txt: '講堂',
        classroomNo: '1',
        top: 1,
        right: 1,
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        4,
        11,
        MapTileType.subroom,
        txt: 'デルタビスタ',
        right: 1,
        bottom: 1,
        food: true,
        drink: true,
        outlet: 1,
      ),
      ConsumerMapTile(20, 11, MapTileType.empty, top: 1, right: 1),
      ConsumerMapTile(2, 9, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.ev, left: 1, top: 1, right: 1),
      ConsumerMapTile(2, 2, MapTileType.empty, right: 1, bottom: 1),
      ConsumerMapTile(6, 2, MapTileType.road, bottom: 1),
    ],
    '5': [
      ConsumerMapTile(
        14,
        2,
        MapTileType.otherroom,
        top: 1,
        left: 1,
        innerWidget: subTile(9, mapCircle7To15TileList),
      ), //サークル1
      ConsumerMapTile(
        2,
        10,
        MapTileType.otherroom,
        right: 1,
        top: 1,
        innerWidget: subTile(5, mapCircle6To1TileList),
      ), //サークル3
      ConsumerMapTile(32, 6, MapTileType.empty), //empty
      ConsumerMapTile(14, 1, MapTileType.road, left: 1),
      ConsumerMapTile(1, 14, MapTileType.road, left: 1),
      ConsumerMapTile(
        11,
        14,
        MapTileType.empty,
        top: 1,
        right: 1,
        bottom: 1,
        left: 1,
      ), //empty gym
      ConsumerMapTile(2, 9, MapTileType.road),
      ConsumerMapTile(2, 6, MapTileType.empty, bottom: 1), //empty
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '595',
        classroomNo: '6',
        top: 1,
        left: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '594',
        classroomNo: '5',
        top: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        6,
        MapTileType.classroom,
        txt: '593',
        classroomNo: '4',
        top: 1,
        right: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(6, 6, MapTileType.empty, bottom: 1, right: 1), //吹き抜け
      ConsumerMapTile(
        6,
        12,
        MapTileType.subroom,
        top: 1,
        right: 1,
        bottom: 1,
        txt: '共同研究室',
      ),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
        top: 1,
        right: 1,
        bottom: 1,
      ), // 階段体育館側
      ConsumerMapTile(30, 1, MapTileType.road),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(
        2,
        5,
        MapTileType.wc,
        wc: 0x1110,
        right: 1,
        bottom: 1,
      ), // 体育館側トイレ
      ConsumerMapTile(2, 5, MapTileType.empty, top: 1), //吹き抜け
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '585',
        classroomNo: '13',
        left: 1,
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '584',
        classroomNo: '12',
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        6,
        5,
        MapTileType.classroom,
        txt: '583',
        classroomNo: '11',
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(2, 5, MapTileType.road),
      ConsumerMapTile(
        2,
        5,
        MapTileType.wc,
        right: 1,
        bottom: 1,
        wc: 0x1100,
      ), // 事務側トイレ
      ConsumerMapTile(2, 5, MapTileType.empty, top: 1, right: 1), //吹き抜け
      ConsumerMapTile(14, 1, MapTileType.road, left: 1),
      ConsumerMapTile(
        12,
        6,
        MapTileType.empty,
        top: 1,
        bottom: 1,
        right: 1,
      ), //empty left
      ConsumerMapTile(2, 6, MapTileType.road),
      ConsumerMapTile(
        22,
        2,
        MapTileType.empty,
        left: 1,
        right: 1,
      ), //empty center1
      ConsumerMapTile(2, 6, MapTileType.road),
      ConsumerMapTile(10, 2, MapTileType.empty, left: 1), //empty right1
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ), // 階段center側
      ConsumerMapTile(18, 2, MapTileType.empty), //empty center2
      ConsumerMapTile(
        2,
        2,
        MapTileType.ev,
        top: 1,
        left: 1,
        bottom: 1,
      ), // エレベーターcenter
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ), // 階段right側
      ConsumerMapTile(8, 2, MapTileType.empty), //empty right2
      ConsumerMapTile(
        22,
        2,
        MapTileType.empty,
        left: 1,
        right: 1,
        bottom: 1,
      ), //empty center3
      ConsumerMapTile(10, 2, MapTileType.empty, left: 1), //empty right3
      ConsumerMapTile(38, 1, MapTileType.road, left: 1),
      ConsumerMapTile(2, 5, MapTileType.otherroom, top: 1, right: 1),
      ConsumerMapTile(2, 5, MapTileType.empty, right: 1, bottom: 1), //吹き抜け
      ConsumerMapTile(2, 5, MapTileType.road, top: 1),
      ConsumerMapTile(
        4,
        8,
        MapTileType.otherroom,
        top: 1,
        right: 1,
        txt: '会議室',
      ),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '536', left: 1),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '535'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '534'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '533'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '532'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '531'),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(2, 4, MapTileType.otherroom, right: 1),
      ConsumerMapTile(2, 4, MapTileType.empty, top: 1, bottom: 1), //吹き抜け
      ConsumerMapTile(1, 4, MapTileType.wc, left: 1, wc: 0x0001),
      ConsumerMapTile(1, 4, MapTileType.road),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '529'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '528'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '527'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '526'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '525'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '524'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '523'),
      ConsumerMapTile(2, 4, MapTileType.teacherroom, txt: '522'),
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(44, 1, MapTileType.road, left: 1),
      ConsumerMapTile(
        12,
        2,
        MapTileType.otherroom,
        left: 1,
        bottom: 1,
      ), //スタジオleft
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.subroom,
        right: 1,
        bottom: 1,
        txt: '大学生協学生委員室',
      ),
      ConsumerMapTile(2, 2, MapTileType.empty, top: 1), //吹き抜け
      ConsumerMapTile(
        18,
        2,
        MapTileType.otherroom,
        left: 1,
        bottom: 1,
      ), //スタジオcenter
      ConsumerMapTile(2, 11, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.subroom,
        right: 1,
        bottom: 1,
        txt: 'M502',
      ),
      ConsumerMapTile(2, 2, MapTileType.empty, top: 1, right: 1), //吹き抜け
      ConsumerMapTile(2, 4, MapTileType.road),
      ConsumerMapTile(12, 12, MapTileType.empty, right: 1), //empty left
      ConsumerMapTile(2, 12, MapTileType.road, bottom: 1),
      ConsumerMapTile(
        22,
        10,
        MapTileType.empty,
        left: 1,
        right: 1,
      ), //empty center
      ConsumerMapTile(
        4,
        9,
        MapTileType.empty,
        left: 1,
        right: 1,
        bottom: 1,
      ), //empty right
      ConsumerMapTile(4, 2, MapTileType.subroom, right: 1, txt: 'M501'),
      ConsumerMapTile(6, 2, MapTileType.road, right: 1),
      ConsumerMapTile(1, 5, MapTileType.road),
      ConsumerMapTile(4, 2, MapTileType.otherroom),
      ConsumerMapTile(1, 5, MapTileType.road, right: 1),
      ConsumerMapTile(4, 3, MapTileType.wc, wc: 0x1110), // 講堂側トイレ
      ConsumerMapTile(12, 1, MapTileType.road, right: 1),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ), // 階段center側
      ConsumerMapTile(20, 2, MapTileType.empty, right: 1), //empty center
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        top: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ), // 階段講堂側
      ConsumerMapTile(2, 2, MapTileType.empty, top: 1, right: 1), //empty 階段横
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(4, 2, MapTileType.otherroom, txt: '調整室'), //調光室
      ConsumerMapTile(1, 2, MapTileType.road, right: 1),
      ConsumerMapTile(36, 12, MapTileType.empty, right: 1), //empty big1
      ConsumerMapTile(2, 12, MapTileType.road, bottom: 1), //empty big1
      ConsumerMapTile(4, 8, MapTileType.empty, left: 1, right: 1), //empty 講堂１
      ConsumerMapTile(
        6,
        12,
        MapTileType.classroom,
        txt: '講堂',
        right: 1,
        bottom: 1,
        food: false,
        drink: true,
        outlet: 2,
      ),
      ConsumerMapTile(
        2,
        2,
        MapTileType.ev,
        left: 1,
        top: 1,
        right: 1,
      ), // エレベーター
      ConsumerMapTile(2, 2, MapTileType.empty, right: 1), //empty ev横
      ConsumerMapTile(2, 1, MapTileType.road, right: 1, bottom: 1), //ev下
      ConsumerMapTile(2, 1, MapTileType.empty, right: 1), //empty ev右下
      ConsumerMapTile(4, 1, MapTileType.empty, left: 1, right: 1), //empty ev下
      ConsumerMapTile(42, 7, MapTileType.empty), //empty ev横
      ConsumerMapTile(6, 7, MapTileType.empty), //empty
    ],
    'R6': [
      ConsumerMapTile(
        4,
        2,
        MapTileType.teacherroom,
        txt: 'R611',
        top: 1,
        left: 1,
      ),
      ConsumerMapTile(1, 30, MapTileType.road, top: 1, bottom: 1),
      ConsumerMapTile(3, 3, MapTileType.otherroom, top: 1),
      ConsumerMapTile(
        3,
        3,
        MapTileType.subroom,
        top: 1,
        txt: 'R627',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(2, 30, MapTileType.road, top: 1, bottom: 1),
      ConsumerMapTile(
        4,
        4,
        MapTileType.subroom,
        top: 1,
        txt: 'R637',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 14, MapTileType.road, top: 1),
      ConsumerMapTile(1, 24, MapTileType.road, top: 1),
      ConsumerMapTile(4, 2, MapTileType.subroom, txt: 'R657', top: 1, right: 1),
      ConsumerMapTile(22, 30, MapTileType.empty),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R610', left: 1),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R656', right: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(4, 2, MapTileType.road, left: 1),
      ConsumerMapTile(3, 20, MapTileType.otherroom),
      ConsumerMapTile(
        3,
        4,
        MapTileType.subroom,
        txt: 'R626',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        4,
        4,
        MapTileType.subroom,
        txt: 'R636',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.road, right: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        left: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        right: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R609', left: 1),
      ConsumerMapTile(
        3,
        4,
        MapTileType.subroom,
        txt: 'R625',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        4,
        3,
        MapTileType.subroom,
        txt: 'R635',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R655', right: 1),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, left: 1, txt: 'R608'),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R654', right: 1),
      ConsumerMapTile(
        4,
        3,
        MapTileType.subroom,
        txt: 'R634',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, left: 1, txt: 'R607'),
      ConsumerMapTile(
        3,
        4,
        MapTileType.subroom,
        txt: 'R624',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R653', right: 1),
      ConsumerMapTile(4, 2, MapTileType.subroom, txt: 'R606', left: 1),
      ConsumerMapTile(4, 2, MapTileType.subroom, txt: 'R633'),
      ConsumerMapTile(4, 2, MapTileType.otherroom),
      ConsumerMapTile(4, 2, MapTileType.subroom, right: 1, txt: 'R652'),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R605', left: 1),
      ConsumerMapTile(
        3,
        4,
        MapTileType.subroom,
        txt: 'R623',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 4, MapTileType.subroom, txt: 'R632'),
      ConsumerMapTile(4, 4, MapTileType.subroom, txt: 'R642'),
      ConsumerMapTile(4, 6, MapTileType.subroom, right: 1, txt: 'R651'),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R604', left: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        left: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: true, down: false),
      ),
      ConsumerMapTile(
        3,
        4,
        MapTileType.subroom,
        txt: 'R622',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(8, 2, MapTileType.road),
      ConsumerMapTile(4, 2, MapTileType.road, left: 1),
      ConsumerMapTile(4, 4, MapTileType.subroom, txt: 'R631'),
      ConsumerMapTile(2, 2, MapTileType.ev),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        left: 1,
        right: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ),
      ConsumerMapTile(4, 2, MapTileType.otherroom, right: 1),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R603', left: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(5, 4, MapTileType.subroom, txt: 'R641', right: 1),
      ConsumerMapTile(4, 6, MapTileType.empty, top: 1),
      ConsumerMapTile(3, 5, MapTileType.otherroom, bottom: 1),
      ConsumerMapTile(
        3,
        3,
        MapTileType.subroom,
        txt: 'R621',
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.subroom, txt: 'R602', left: 1),
      ConsumerMapTile(4, 4, MapTileType.wc, wc: 0x1110, bottom: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.teacherroom,
        txt: 'R601',
        left: 1,
        bottom: 1,
      ),
      ConsumerMapTile(2, 2, MapTileType.otherroom, bottom: 1),
      ConsumerMapTile(1, 2, MapTileType.otherroom, bottom: 1),
      ConsumerMapTile(4, 2, MapTileType.subroom, bottom: 1),
      ConsumerMapTile(1, 2, MapTileType.subroom, bottom: 1, right: 1),
    ],
    'R7': [
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R711',
        top: 1,
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(1, 30, MapTileType.road, top: 1, bottom: 1),
      ConsumerMapTile(3, 3, MapTileType.empty, bottom: 1, left: 1),
      ConsumerMapTile(2, 3, MapTileType.otherroom, left: 1, top: 1, right: 1),
      ConsumerMapTile(3, 3, MapTileType.empty, bottom: 1),
      ConsumerMapTile(2, 3, MapTileType.empty),
      ConsumerMapTile(2, 9, MapTileType.otherroom, left: 1, top: 1, right: 1),
      ConsumerMapTile(4, 9, MapTileType.empty, right: 1, bottom: 1),
      ConsumerMapTile(1, 14, MapTileType.road, top: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.teacherroom,
        txt: 'R757',
        top: 1,
        right: 1,
      ),
      ConsumerMapTile(22, 20, MapTileType.empty, bottom: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R710',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 2, MapTileType.teacherroom, txt: 'R756', right: 1),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(2, 22, MapTileType.road),
      ConsumerMapTile(2, 6, MapTileType.empty, left: 1, bottom: 1),
      ConsumerMapTile(4, 2, MapTileType.road, left: 1),
      ConsumerMapTile(6, 4, MapTileType.empty, left: 1, top: 1, right: 1),
      ConsumerMapTile(4, 2, MapTileType.road, right: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        left: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        right: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R709',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(4, 12, MapTileType.empty, left: 1),
      ConsumerMapTile(
        2,
        4,
        MapTileType.subroom,
        txt: 'R725',
        left: 1,
        top: 1,
        food: false,
        drink: true,
        outlet: 0,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R755',
        right: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(8, 1, MapTileType.road),
      ConsumerMapTile(4, 4, MapTileType.otherroom, left: 1),
      ConsumerMapTile(
        8,
        4,
        MapTileType.empty,
        left: 1,
        top: 1,
        right: 1,
        bottom: 1,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R754',
        right: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        2,
        4,
        MapTileType.subroom,
        txt: 'R724',
        left: 1,
        food: false,
        drink: true,
        outlet: 0,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R753',
        right: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R706',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(2, 2, MapTileType.otherroom),
      ConsumerMapTile(2, 2, MapTileType.otherroom),
      ConsumerMapTile(9, 6, MapTileType.otherroom, right: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R705',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        2,
        4,
        MapTileType.subroom,
        txt: 'R723',
        left: 1,
        bottom: 1,
        food: false,
        drink: true,
        outlet: 0,
      ),
      ConsumerMapTile(
        4,
        4,
        MapTileType.subroom,
        txt: 'R731',
        food: false,
        drink: true,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R704',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        4,
        2,
        MapTileType.stair,
        left: 1,
        top: 1,
        bottom: 1,
        stairType: const MapStairType(Axis.horizontal, up: false, down: true),
      ),
      ConsumerMapTile(6, 4, MapTileType.empty, left: 1, bottom: 1, right: 1),
      ConsumerMapTile(30, 2, MapTileType.road),
      ConsumerMapTile(
        5,
        10,
        MapTileType.classroom,
        txt: 'R791',
        right: 1,
        bottom: 1,
        classroomNo: '7',
        food: false,
        drink: true,
        outlet: 1,
      ),
      ConsumerMapTile(4, 2, MapTileType.road, left: 1),
      ConsumerMapTile(3, 3, MapTileType.empty, left: 1, top: 1, right: 1),
      ConsumerMapTile(1, 7, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.ev),
      ConsumerMapTile(
        2,
        2,
        MapTileType.stair,
        left: 1,
        right: 1,
        stairType: const MapStairType(Axis.vertical, up: false, down: true),
      ),
      ConsumerMapTile(1, 2, MapTileType.otherroom),
      ConsumerMapTile(4, 2, MapTileType.subroom, txt: 'R751'),
      ConsumerMapTile(5, 2, MapTileType.otherroom),
      ConsumerMapTile(
        4,
        8,
        MapTileType.classroom,
        txt: 'R781',
        classroomNo: '14',
        bottom: 1,
        food: false,
        drink: true,
        outlet: 1,
      ),
      ConsumerMapTile(
        4,
        8,
        MapTileType.classroom,
        txt: 'R782',
        classroomNo: '15',
        bottom: 1,
        food: false,
        drink: true,
        outlet: 1,
      ),
      ConsumerMapTile(2, 2, MapTileType.ev),
      ConsumerMapTile(2, 2, MapTileType.road),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R703',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(6, 1, MapTileType.road),
      ConsumerMapTile(5, 4, MapTileType.empty, top: 1, left: 1),
      ConsumerMapTile(9, 6, MapTileType.empty, right: 1, top: 1),
      ConsumerMapTile(4, 2, MapTileType.road),
      ConsumerMapTile(3, 5, MapTileType.empty, top: 1, left: 1),
      ConsumerMapTile(2, 5, MapTileType.otherroom, bottom: 1, left: 1),
      ConsumerMapTile(3, 3, MapTileType.empty, left: 1, top: 1),
      ConsumerMapTile(3, 1, MapTileType.empty, right: 1),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R702',
        left: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(
        3,
        4,
        MapTileType.wc,
        left: 1,
        top: 1,
        bottom: 1,
        wc: 0x1100,
      ),
      ConsumerMapTile(
        1,
        2,
        MapTileType.stair,
        right: 1,
        bottom: 1,
        left: 1,
        stairType: const MapStairType(Axis.vertical, up: true, down: false),
      ),
      ConsumerMapTile(1, 2, MapTileType.road),
      ConsumerMapTile(2, 2, MapTileType.wc, wc: 0x0010),
      ConsumerMapTile(
        4,
        2,
        MapTileType.subroom,
        txt: 'R701',
        left: 1,
        bottom: 1,
        food: true,
        drink: true,
      ),
      ConsumerMapTile(1, 2, MapTileType.otherroom, right: 1, top: 1, bottom: 1),
      ConsumerMapTile(2, 2, MapTileType.empty),
      ConsumerMapTile(5, 2, MapTileType.otherroom, bottom: 1, right: 1, top: 1),
      ConsumerMapTile(2, 2, MapTileType.wc, bottom: 1, wc: 0x0100),
      ConsumerMapTile(2, 2, MapTileType.wc, bottom: 1, wc: 0x1000),
      ConsumerMapTile(1, 1, MapTileType.wc, bottom: 1),
    ],
  };

  static final List<ConsumerMapTile> mapCircle7To15TileList = [
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室15',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室14',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室13',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室12',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室11',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室10',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室9',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室8',
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      1,
      1,
      MapTileType.subroom,
      txt: 'サークル室7',
      food: true,
      drink: true,
      outlet: 2,
    ),
  ];

  static final List<ConsumerMapTile> mapCircle6To1TileList = [
    ConsumerMapTile(
      5,
      8,
      MapTileType.subroom,
      txt: 'サークル室6',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      5,
      4,
      MapTileType.subroom,
      txt: 'サークル室5',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      5,
      4,
      MapTileType.subroom,
      txt: 'サークル室4',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      5,
      4,
      MapTileType.subroom,
      txt: 'サークル室3',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      5,
      4,
      MapTileType.subroom,
      txt: 'サークル室2',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
    ConsumerMapTile(
      5,
      4,
      MapTileType.subroom,
      txt: 'サークル室1',
      fontSize: 3,
      food: true,
      drink: true,
      outlet: 2,
    ),
  ];

  static Widget subTile(int count, List<ConsumerMapTile> tileList) {
    return StaggeredGrid.count(
      crossAxisCount: count,
      children: [
        ...tileList.map((e) {
          return StaggeredGridTile.count(
            crossAxisCellCount: e.width,
            mainAxisCellCount: e.height,
            child: e,
          );
        }),
      ],
    );
  }
}
