# https://taskfile.dev

version: "3"

vars:
  FLUTTER: flutter
  DART: dart

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: Install dependencies and configure Flutter
    cmds:
      - "{{.FLUTTER}} config --enable-swift-package-manager"
      - "{{.FLUTTER}} pub get"

  build:
    desc: Run build_runner to generate code
    cmds:
      - "{{.DART}} run build_runner build --delete-conflicting-outputs"

  watch:
    desc: Run build_runner to generate code in watch mode
    cmds:
      - "{{.DART}} run build_runner watch --delete-conflicting-outputs"

  run:
    desc: Run the Flutter app
    cmds:
      - task: build
      - "{{.FLUTTER}} run -d chrome"
