// Mocks generated by Mockito 5.4.6 from annotations
// in dotto/test/feature/map/map_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dotto/domain/room.dart' as _i4;
import 'package:dotto/repository/room_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'map_viewmodel_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RoomRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomRepository extends _i1.Mock implements _i2.RoomRepository {
  MockRoomRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Room>> getRooms() =>
      (super.noSuchMethod(
            Invocation.method(#getRooms, []),
            returnValue: _i3.Future<List<_i4.Room>>.value(<_i4.Room>[]),
          )
          as _i3.Future<List<_i4.Room>>);
}

/// A class which mocks [Listener].
///
/// See the documentation for Mockito's code generation for more information.
class MockListener<T> extends _i1.Mock implements _i5.Listener<T> {
  MockListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(T? previous, T? next) => super.noSuchMethod(
    Invocation.method(#call, [previous, next]),
    returnValueForMissingStub: null,
  );
}
