# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :deploy do
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_testflight
  end

  desc "Match development"
  lane :match_development do
    match(
      type: "development",
      force_for_new_devices: true
    )
  end

  desc "Match adhoc"
  lane :match_adhoc do
    match(
      type: "adhoc",
      force_for_new_devices: true
    )
  end

  desc "Match appstore"
  lane :match_appstore do
    match(
      type: "appstore",
      force_for_new_devices: true
    )
  end

  desc "Match development (readonly)"
  lane :match_development_readonly do
    match(
      type: "development",
      readonly: true,
      force_for_new_devices: true
    )
  end

  desc "Match adhoc (readonly)"
  lane :match_adhoc_readonly do
    match(
      type: "adhoc",
      readonly: true,
      force_for_new_devices: true
    )
  end

  desc "Match appstore (readonly)"
  lane :match_appstore_readonly do
    match(
      type: "appstore",
      readonly: true,
      force_for_new_devices: true
    )
  end
end
