# https://taskfile.dev

version: "3"

vars:
  FLUTTER: fvm flutter
  DART: fvm dart
  FASTLANE: bundle exec fastlane

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  install:
    desc: Install dependencies and configure Flutter
    cmds:
      - "{{.FLUTTER}} pub get"

  build:
    desc: Run build_runner to generate code
    cmds:
      - "{{.DART}} run build_runner build --delete-conflicting-outputs"
